services:
  # PostgreSQL Database for development
  database:
    image: postgres:15-alpine
    container_name: todo-database-dev
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

  # H2 Database for quick testing
  h2-console:
    image: oscarfonts/h2
    container_name: todo-h2-console
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: -web -webAllowOthers -tcp -tcpAllowOthers -browser
    networks:
      - todo-network

volumes:
  postgres_data_dev:
    driver: local

networks:
  todo-network:
    driver: bridge
