CREATE TABLE todos (
   id BIGSERIAL PRIMARY KEY,
   description VARCHAR(255) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   due_date TIMESTAMP,
   done BOOLEAN DEFAULT FALSE
);
